export type Company = {
    id: string
    // Identity
    companyName: string
    ein: string
    companyPhone: string
    website: string
    companyLinkedin: string

    // Location
    hqLocation: string
    companyAddress1: string
    companyAddress2: string
    companyCity: string
    companyState: string
    companyZip: string
    companyCounty: string

    // Financials
    modeledRevenue: string
    reportedPremiums: string
    modeledPremium: string
    totalCommission: string
    totalFees: string
    reportedBrokerComp: string
    modeledBrokerComp: string

    // Participants
    eligibleParticipants: number
    participantsSummed: number

    // Carriers
    topCarrier: string
    topCarrierPercent: string
    timeWithTopCarrier: string
    primaryMedicalCarrier: string
    primaryMedicalCarrierWebsite: string

    // Brokers
    topBroker: string
    topBrokerPercent: string
    timeWithTopBroker: string
    secondBroker: string
    thirdBroker: string

    // Plan Details
    planAttributes: string[]
    planTypes: string[]
    selfFunded: boolean
    fidelityBond: string
    signer5500: string
    filingStatus: string
    filingIssue: string
    filingType: string

    // Ratings
    benefitRating: string
    overallRating: string
    retentionRisk: "Low" | "Medium" | "High"

    // Industry
    industryCode: string
    industryName: string
    industrySegment: string

    // Other
    renewalDate: string // ISO date string
    recentJobChange: boolean
    accountingFirm: string
    keyContacts: string[]
}

export const mockCompanies: Company[] = [
    {
        id: "1",
        companyName: "Acme Corp",
        ein: "12-3456789",
        companyPhone: "(512) 555-0123",
        website: "acme.com",
        companyLinkedin: "linkedin.com/company/acme-corp",
        hqLocation: "Austin, TX",
        companyAddress1: "123 Main St",
        companyAddress2: "Suite 100",
        companyCity: "Austin",
        companyState: "TX",
        companyZip: "78701",
        companyCounty: "Travis",
        modeledRevenue: "$75,000,000",
        reportedPremiums: "$2,500,000",
        modeledPremium: "$2,600,000",
        totalCommission: "$150,000",
        totalFees: "$25,000",
        reportedBrokerComp: "$175,000",
        modeledBrokerComp: "$180,000",
        eligibleParticipants: 1250,
        participantsSummed: 1200,
        topCarrier: "BlueCross BlueShield",
        topCarrierPercent: "85%",
        timeWithTopCarrier: "5 Years",
        primaryMedicalCarrier: "BlueCross BlueShield",
        primaryMedicalCarrierWebsite: "bcbs.com",
        topBroker: "Marsh & McLennan",
        topBrokerPercent: "100%",
        timeWithTopBroker: "3 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["401(k)", "Dental", "Vision"],
        planTypes: ["Health", "Welfare"],
        selfFunded: true,
        fidelityBond: "$1,000,000",
        signer5500: "John Doe",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "A",
        overallRating: "A+",
        retentionRisk: "Low",
        industryCode: "333",
        industryName: "Machinery Manufacturing",
        industrySegment: "Manufacturing",
        renewalDate: "2024-01-01",
        recentJobChange: false,
        accountingFirm: "Deloitte",
        keyContacts: ["Jane Smith (HR)", "Bob Jones (CFO)"]
    },
    {
        id: "2",
        companyName: "TechNova",
        ein: "98-7654321",
        companyPhone: "(415) 555-0987",
        website: "technova.io",
        companyLinkedin: "linkedin.com/company/technova",
        hqLocation: "San Francisco, CA",
        companyAddress1: "456 Tech Way",
        companyAddress2: "Floor 12",
        companyCity: "San Francisco",
        companyState: "CA",
        companyZip: "94105",
        companyCounty: "San Francisco",
        modeledRevenue: "$45,000,000",
        reportedPremiums: "$1,200,000",
        modeledPremium: "$1,300,000",
        totalCommission: "$80,000",
        totalFees: "$10,000",
        reportedBrokerComp: "$90,000",
        modeledBrokerComp: "$95,000",
        eligibleParticipants: 340,
        participantsSummed: 320,
        topCarrier: "UnitedHealthcare",
        topCarrierPercent: "90%",
        timeWithTopCarrier: "2 Years",
        primaryMedicalCarrier: "UnitedHealthcare",
        primaryMedicalCarrierWebsite: "uhc.com",
        topBroker: "Aon",
        topBrokerPercent: "100%",
        timeWithTopBroker: "2 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["401(k)", "Stock Options"],
        planTypes: ["Health", "Welfare", "Pension"],
        selfFunded: false,
        fidelityBond: "$500,000",
        signer5500: "Alice Wonderland",
        filingStatus: "Filed",
        filingIssue: "Late Filing",
        filingType: "Form 5500",
        benefitRating: "B+",
        overallRating: "B",
        retentionRisk: "High",
        industryCode: "5112",
        industryName: "Software Publishers",
        industrySegment: "Technology",
        renewalDate: "2024-03-15",
        recentJobChange: true,
        accountingFirm: "PwC",
        keyContacts: ["Charlie Brown (CTO)"]
    },
    {
        id: "3",
        companyName: "GreenLeaf Health",
        ein: "45-1234567",
        companyPhone: "(303) 555-1122",
        website: "greenleaf.org",
        companyLinkedin: "linkedin.com/company/greenleaf",
        hqLocation: "Denver, CO",
        companyAddress1: "789 Nature Blvd",
        companyAddress2: "",
        companyCity: "Denver",
        companyState: "CO",
        companyZip: "80202",
        companyCounty: "Denver",
        modeledRevenue: "$8,000,000",
        reportedPremiums: "$400,000",
        modeledPremium: "$420,000",
        totalCommission: "$25,000",
        totalFees: "$5,000",
        reportedBrokerComp: "$30,000",
        modeledBrokerComp: "$32,000",
        eligibleParticipants: 85,
        participantsSummed: 80,
        topCarrier: "Aetna",
        topCarrierPercent: "100%",
        timeWithTopCarrier: "6 Years",
        primaryMedicalCarrier: "Aetna",
        primaryMedicalCarrierWebsite: "aetna.com",
        topBroker: "Gallagher",
        topBrokerPercent: "100%",
        timeWithTopBroker: "6 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["Health", "Dental"],
        planTypes: ["Welfare"],
        selfFunded: false,
        fidelityBond: "$250,000",
        signer5500: "Sarah Green",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500-SF",
        benefitRating: "B",
        overallRating: "B",
        retentionRisk: "Medium",
        industryCode: "621",
        industryName: "Ambulatory Health Care Services",
        industrySegment: "Healthcare",
        renewalDate: "2024-06-01",
        recentJobChange: false,
        accountingFirm: "Local CPA",
        keyContacts: ["Dr. Smith (CEO)"]
    },
    {
        id: "4",
        companyName: "Stark Industries",
        ein: "10-0000001",
        companyPhone: "(212) 555-9999",
        website: "stark.com",
        companyLinkedin: "linkedin.com/company/stark-industries",
        hqLocation: "New York, NY",
        companyAddress1: "890 Fifth Avenue",
        companyAddress2: "Stark Tower",
        companyCity: "New York",
        companyState: "NY",
        companyZip: "10021",
        companyCounty: "New York",
        modeledRevenue: "$25,000,000,000",
        reportedPremiums: "$500,000,000",
        modeledPremium: "$550,000,000",
        totalCommission: "$20,000,000",
        totalFees: "$5,000,000",
        reportedBrokerComp: "$25,000,000",
        modeledBrokerComp: "$28,000,000",
        eligibleParticipants: 50000,
        participantsSummed: 48000,
        topCarrier: "Cigna",
        topCarrierPercent: "60%",
        timeWithTopCarrier: "10 Years",
        primaryMedicalCarrier: "Cigna",
        primaryMedicalCarrierWebsite: "cigna.com",
        topBroker: "Willis Towers Watson",
        topBrokerPercent: "50%",
        timeWithTopBroker: "10 Years",
        secondBroker: "Marsh",
        thirdBroker: "Aon",
        planAttributes: ["401(k)", "Pension", "Executive Comp"],
        planTypes: ["Health", "Welfare", "Pension"],
        selfFunded: true,
        fidelityBond: "$50,000,000",
        signer5500: "Pepper Potts",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "A+",
        overallRating: "A+",
        retentionRisk: "Low",
        industryCode: "3364",
        industryName: "Aerospace Product and Parts Manufacturing",
        industrySegment: "Defense",
        renewalDate: "2024-01-01",
        recentJobChange: true,
        accountingFirm: "KPMG",
        keyContacts: ["Tony Stark (Owner)", "Happy Hogan (Security)"]
    },
    {
        id: "5",
        companyName: "Dunder Mifflin",
        ein: "33-4455667",
        companyPhone: "(570) 555-0444",
        website: "dundermifflin.com",
        companyLinkedin: "linkedin.com/company/dunder-mifflin",
        hqLocation: "Scranton, PA",
        companyAddress1: "1725 Slough Avenue",
        companyAddress2: "Suite 200",
        companyCity: "Scranton",
        companyState: "PA",
        companyZip: "18503",
        companyCounty: "Lackawanna",
        modeledRevenue: "$40,000,000",
        reportedPremiums: "$900,000",
        modeledPremium: "$950,000",
        totalCommission: "$50,000",
        totalFees: "$5,000",
        reportedBrokerComp: "$55,000",
        modeledBrokerComp: "$60,000",
        eligibleParticipants: 150,
        participantsSummed: 145,
        topCarrier: "BlueCross BlueShield",
        topCarrierPercent: "95%",
        timeWithTopCarrier: "15 Years",
        primaryMedicalCarrier: "BlueCross BlueShield",
        primaryMedicalCarrierWebsite: "bcbs.com",
        topBroker: "Local Brokerage",
        topBrokerPercent: "100%",
        timeWithTopBroker: "15 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["Health", "Dental"],
        planTypes: ["Welfare"],
        selfFunded: false,
        fidelityBond: "$100,000",
        signer5500: "Michael Scott",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "C",
        overallRating: "C+",
        retentionRisk: "Medium",
        industryCode: "4241",
        industryName: "Paper and Paper Product Merchant Wholesalers",
        industrySegment: "Retail",
        renewalDate: "2024-11-01",
        recentJobChange: false,
        accountingFirm: "Oscar Martinez CPA",
        keyContacts: ["David Wallace (CFO)", "Dwight Schrute (Sales)"]
    },
    {
        id: "6",
        companyName: "Cyberdyne Systems",
        ein: "99-8877665",
        companyPhone: "(408) 555-0001",
        website: "cyberdyne.com",
        companyLinkedin: "linkedin.com/company/cyberdyne",
        hqLocation: "Sunnyvale, CA",
        companyAddress1: "18144 El Camino Real",
        companyAddress2: "",
        companyCity: "Sunnyvale",
        companyState: "CA",
        companyZip: "94087",
        companyCounty: "Santa Clara",
        modeledRevenue: "$12,000,000,000",
        reportedPremiums: "$300,000,000",
        modeledPremium: "$320,000,000",
        totalCommission: "$15,000,000",
        totalFees: "$2,000,000",
        reportedBrokerComp: "$17,000,000",
        modeledBrokerComp: "$18,000,000",
        eligibleParticipants: 8000,
        participantsSummed: 7800,
        topCarrier: "Kaiser Permanente",
        topCarrierPercent: "75%",
        timeWithTopCarrier: "8 Years",
        primaryMedicalCarrier: "Kaiser Permanente",
        primaryMedicalCarrierWebsite: "kp.org",
        topBroker: "Mercer",
        topBrokerPercent: "60%",
        timeWithTopBroker: "4 Years",
        secondBroker: "Aon",
        thirdBroker: "",
        planAttributes: ["401(k)", "AI Research Grant"],
        planTypes: ["Health", "Welfare", "Pension"],
        selfFunded: true,
        fidelityBond: "$10,000,000",
        signer5500: "Miles Dyson",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "A",
        overallRating: "A",
        retentionRisk: "High",
        industryCode: "5417",
        industryName: "Scientific Research and Development Services",
        industrySegment: "Technology",
        renewalDate: "2024-08-29",
        recentJobChange: true,
        accountingFirm: "Ernst & Young",
        keyContacts: ["Miles Dyson (Director)"]
    },
    {
        id: "7",
        companyName: "Wayne Enterprises",
        ein: "11-2233445",
        companyPhone: "(973) 555-0199",
        website: "wayne-ent.com",
        companyLinkedin: "linkedin.com/company/wayne-enterprises",
        hqLocation: "Gotham, NJ",
        companyAddress1: "1007 Mountain Drive",
        companyAddress2: "",
        companyCity: "Gotham",
        companyState: "NJ",
        companyZip: "07001",
        companyCounty: "Essex",
        modeledRevenue: "$50,000,000,000",
        reportedPremiums: "$800,000,000",
        modeledPremium: "$850,000,000",
        totalCommission: "$40,000,000",
        totalFees: "$10,000,000",
        reportedBrokerComp: "$50,000,000",
        modeledBrokerComp: "$55,000,000",
        eligibleParticipants: 100000,
        participantsSummed: 98000,
        topCarrier: "MetLife",
        topCarrierPercent: "50%",
        timeWithTopCarrier: "20 Years",
        primaryMedicalCarrier: "MetLife",
        primaryMedicalCarrierWebsite: "metlife.com",
        topBroker: "Willis Towers Watson",
        topBrokerPercent: "40%",
        timeWithTopBroker: "15 Years",
        secondBroker: "Marsh",
        thirdBroker: "Gallagher",
        planAttributes: ["401(k)", "Pension", "Executive Comp", "Charity Match"],
        planTypes: ["Health", "Welfare", "Pension"],
        selfFunded: true,
        fidelityBond: "$100,000,000",
        signer5500: "Lucius Fox",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "A+",
        overallRating: "A+",
        retentionRisk: "Low",
        industryCode: "5511",
        industryName: "Management of Companies and Enterprises",
        industrySegment: "Conglomerate",
        renewalDate: "2024-01-01",
        recentJobChange: false,
        accountingFirm: "Deloitte",
        keyContacts: ["Bruce Wayne (CEO)", "Lucius Fox (CEO)"]
    },
    {
        id: "8",
        companyName: "Massive Dynamic",
        ein: "55-6677889",
        companyPhone: "(212) 555-1234",
        website: "massivedynamic.com",
        companyLinkedin: "linkedin.com/company/massive-dynamic",
        hqLocation: "New York, NY",
        companyAddress1: "666 5th Avenue",
        companyAddress2: "",
        companyCity: "New York",
        companyState: "NY",
        companyZip: "10103",
        companyCounty: "New York",
        modeledRevenue: "$15,000,000,000",
        reportedPremiums: "$400,000,000",
        modeledPremium: "$410,000,000",
        totalCommission: "$20,000,000",
        totalFees: "$3,000,000",
        reportedBrokerComp: "$23,000,000",
        modeledBrokerComp: "$25,000,000",
        eligibleParticipants: 12000,
        participantsSummed: 11500,
        topCarrier: "Aetna",
        topCarrierPercent: "80%",
        timeWithTopCarrier: "5 Years",
        primaryMedicalCarrier: "Aetna",
        primaryMedicalCarrierWebsite: "aetna.com",
        topBroker: "Aon",
        topBrokerPercent: "90%",
        timeWithTopBroker: "5 Years",
        secondBroker: "Marsh",
        thirdBroker: "",
        planAttributes: ["401(k)", "Stock Options", "Wellness Program"],
        planTypes: ["Health", "Welfare"],
        selfFunded: true,
        fidelityBond: "$20,000,000",
        signer5500: "Nina Sharp",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "A",
        overallRating: "A-",
        retentionRisk: "High",
        industryCode: "5417",
        industryName: "Scientific Research and Development Services",
        industrySegment: "Technology",
        renewalDate: "2024-05-15",
        recentJobChange: true,
        accountingFirm: "PwC",
        keyContacts: ["William Bell (Founder)", "Nina Sharp (COO)"]
    },
    {
        id: "9",
        companyName: "Soylent Corp",
        ein: "22-3344556",
        companyPhone: "(212) 555-5678",
        website: "soylent.com",
        companyLinkedin: "linkedin.com/company/soylent-corp",
        hqLocation: "New York, NY",
        companyAddress1: "123 Food Drive",
        companyAddress2: "",
        companyCity: "New York",
        companyState: "NY",
        companyZip: "10001",
        companyCounty: "New York",
        modeledRevenue: "$5,000,000,000",
        reportedPremiums: "$150,000,000",
        modeledPremium: "$160,000,000",
        totalCommission: "$8,000,000",
        totalFees: "$1,000,000",
        reportedBrokerComp: "$9,000,000",
        modeledBrokerComp: "$10,000,000",
        eligibleParticipants: 5000,
        participantsSummed: 4900,
        topCarrier: "UnitedHealthcare",
        topCarrierPercent: "90%",
        timeWithTopCarrier: "12 Years",
        primaryMedicalCarrier: "UnitedHealthcare",
        primaryMedicalCarrierWebsite: "uhc.com",
        topBroker: "Marsh",
        topBrokerPercent: "100%",
        timeWithTopBroker: "12 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["Health", "Dental", "Vision"],
        planTypes: ["Welfare"],
        selfFunded: false,
        fidelityBond: "$5,000,000",
        signer5500: "Simmonds",
        filingStatus: "Filed",
        filingIssue: "None",
        filingType: "Form 5500",
        benefitRating: "B-",
        overallRating: "C",
        retentionRisk: "Medium",
        industryCode: "311",
        industryName: "Food Manufacturing",
        industrySegment: "Manufacturing",
        renewalDate: "2024-10-31",
        recentJobChange: false,
        accountingFirm: "KPMG",
        keyContacts: ["Governor Santini (Board Member)"]
    },
    {
        id: "10",
        companyName: "Umbrella Corp",
        ein: "66-7788990",
        companyPhone: "(212) 555-6666",
        website: "umbrella.com",
        companyLinkedin: "linkedin.com/company/umbrella-corp",
        hqLocation: "Raccoon City, MO",
        companyAddress1: "5432 Virus Lane",
        companyAddress2: "Underground Lab",
        companyCity: "Raccoon City",
        companyState: "MO",
        companyZip: "63101",
        companyCounty: "St. Louis",
        modeledRevenue: "$9,000,000,000",
        reportedPremiums: "$250,000,000",
        modeledPremium: "$260,000,000",
        totalCommission: "$12,000,000",
        totalFees: "$2,500,000",
        reportedBrokerComp: "$14,500,000",
        modeledBrokerComp: "$15,000,000",
        eligibleParticipants: 6000,
        participantsSummed: 5800,
        topCarrier: "Cigna",
        topCarrierPercent: "85%",
        timeWithTopCarrier: "7 Years",
        primaryMedicalCarrier: "Cigna",
        primaryMedicalCarrierWebsite: "cigna.com",
        topBroker: "Gallagher",
        topBrokerPercent: "95%",
        timeWithTopBroker: "3 Years",
        secondBroker: "",
        thirdBroker: "",
        planAttributes: ["Health", "Life", "Hazard Pay"],
        planTypes: ["Welfare"],
        selfFunded: true,
        fidelityBond: "$15,000,000",
        signer5500: "Albert Wesker",
        filingStatus: "Filed",
        filingIssue: "Investigation Pending",
        filingType: "Form 5500",
        benefitRating: "B",
        overallRating: "B-",
        retentionRisk: "High",
        industryCode: "3254",
        industryName: "Pharmaceutical and Medicine Manufacturing",
        industrySegment: "Healthcare",
        renewalDate: "2024-07-15",
        recentJobChange: true,
        accountingFirm: "Arthur Andersen (Legacy)",
        keyContacts: ["Albert Wesker (Researcher)", "William Birkin (Scientist)"]
    }
]
